INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE) VALUES ('teste1', 'teste2', 'teste3')
INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE) VALUES ('teste1', 'teste2', 'teste3')
INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE) VALUES ('teste1', 'teste2', 'teste3')

