INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE, DATE_REGISTER) VALUES ('teste1-REPORT_VICTIM', 'teste1-VIOLATION_VICTIM', 'teste1-PROVIDENCE', TIMESTAMP WITH TIME ZONE '2023-06-16T19:19:00Z')
INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE, DATE_REGISTER) VALUES ('teste2-REPORT_VICTIM', 'teste2-VIOLATION_VICTIM', 'teste2-PROVIDENCE', TIMESTAMP WITH TIME ZONE '2024-06-16T19:19:00Z')
INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE, DATE_REGISTER) VALUES ('teste3-REPORT_VICTIM', 'teste3-VIOLATION_VICTIM', 'teste3-PROVIDENCE', TIMESTAMP WITH TIME ZONE '2025-06-16T19:19:00Z')
INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE, DATE_REGISTER) VALUES ('teste4-REPORT_VICTIM', 'teste4-VIOLATION_VICTIM', 'teste4-PROVIDENCE', TIMESTAMP WITH TIME ZONE '2026-06-16T19:19:00Z')
INSERT INTO TB_INCIDENT (REPORT_VICTIM,VIOLATION_VICTIM,PROVIDENCE, DATE_REGISTER) VALUES ('teste5-REPORT_VICTIM', 'teste5-VIOLATION_VICTIM', 'teste5-PROVIDENCE', TIMESTAMP WITH TIME ZONE '2027-06-16T19:19:00Z')

